### ISSUE TITLE
Add example card xml

### ISSUE THREAD

**Issue by snickercop** [snickercop/cardizer#2]
Follow the instructions in the docs to make an xml file with example cards, and make sure the program works on it!

**Comment by zyjeng11** [comment]
I'd like to work on this issue, can I get more detail information?

**Comment by snickercop** [comment]
You should make an xml file containing data for two or three cards. Then, run the xmlparse.py script on them. You should see some images with the card text spit out. If it works, send me a merge request!

**Comment by zyjeng11** [comment]
I got a error message while execute xmlparse.py and I've stuck here.
Traceback (most recent call last):
  File "xmlparse.py", line 1, in <module>
    from card import Card, filize
  File "D:\python\cardizer-master\card.py", line 10, in <module>
    rulesF = ImageFont.truetype('fonts/source-code-pro/SourceCodePro-Medium.otf', RULES_FONT_SIZE)
  File "D:\program\python\lib\site-packages\PIL\ImageFont.py", line 640, in truetype
    return freetype(font)
  File "D:\program\python\lib\site-packages\PIL\ImageFont.py", line 637, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\program\python\lib\site-packages\PIL\ImageFont.py", line 186, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

**Comment by zyjeng11** [comment]
I found the problem. In card.py line 9, 10, I need to write the direct path of the font file. 
FYI

**Comment by snickercop** [comment]
It's probably because the import path for the font is different on your
computer. Also, you gotta make sure that thing is downloaded.

If all else fails, just delete any code that references font and the cards
should print with the default font; it'll be ugly but it's just for testing
so it's ok.

**Comment by snickercop** [comment]
Oh yeah, you got it! I replied from my email and github hadn't sent your latest reply yet. Good job :)

**Comment by zyjeng11** [comment]
Did you receive my PR? I'm I doing it right?
